[package]
name = "PQ_Signal"
version = "0.1.0"
edition = "2021"
authors = ["Moha"]

[dependencies]
rand = "0.8"
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
ed25519-dalek = { version = "2.1.1"}
hkdf = "0.12.4"
sha2 = "0.10.8"
p256={version = "0.13.2", features = ["ecdh"]} 
hex="0.4.3"